# https://jekyllrb.com/docs/configuration/

# site-wide variables
title: CAISA Lab # title of site, used in tab name and elsewhere
email: lucie.flek@gmail.com # default email
google: Lucie Flek # default name to search on Google Scholar
github: caisa-lab # default GitHub user/org, without the @
twitter: lucie_nlp # default Twitter handle, without the @
instagram: fakeinstagramhandle # default Instagram handle, without the @
youtube: fakeyoutubechannel # default YouTube channel handle

# base directory where site is hosted
# set to "" if hosting at a custom domain, eg yoursite.com
baseurl: ""

# default front matter parameters for markdown files
# defaults can be overridden on a particular page, eg:
# ---
# description: Description unique to this page
# background: images/different-bg-for-this-page.jpg
# ---
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: In the Conversational AI and Social Analytics (CAISA) Lab, we combine diverse expertise from areas such as natural language processing, machine learning, and computational social sciences, on a mission to understand people behind the language. # description that will show under search engine results
      background: images/test-tube.jpg # background image in header and footer
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
